### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by rogu2**
This feature branch adds initial index.html, auth javascript, limited styling.

HTML:
- Nav Bar
- Modal Forms for Sign-Up, Sign-In, Change-Password 
- Sign-Out Button
- User Message (action feedback) area, to be used for resources as well.

JavaScript:
- Auth CRUD scripts: Sign-up, Sign-in, Sign-out, Change-Password
- Event Handler for Auth Events
- UI for Auth Events

Curl Scripts:
- Auth sign-up
- Auth sign-in
- Auth change-password
- Auth sign-out

Future versions may contain: Auto Sign-In following successful Sign-up.

### CODE REVIEW

**Comment by juliojesse25** [comment]
I have reviewed this and it looks good to me

**Comment by zzyyfff** [comment]
Check that all user auth functions work with the backend API first.

**Comment by rogu2** [comment]
Confirmed Curl Scripts worked. Confirmed Auth Front End works. Ready to merge!

**Review by juliojesse25 — APPROVED** [review]
It looks good to me. I think we can merge this

**Pull request merged**
